/// <reference path="./types/mulby.d.ts" />

// ─── 类型 ───────────────────────────────────────────
interface CommitEntry {
  hash: string
  author: string
  email: string
  date: string
  subject: string
}

interface RepoInfo {
  name: string
  path: string
  remoteUrl: string
  branch: string
  isRepo: boolean
  error?: string
}

interface GitLogResult {
  commits: CommitEntry[]
  total: number
  since: string
  until: string
}

interface ContributorStat {
  name: string
  email: string
  count: number
}

interface DiffStat {
  filesChanged: number
  insertions: number
  deletions: number
  details: string
}

interface GenerateReportInput {
  projectPath?: string
  projectPaths?: string[]
  reportType: 'daily' | 'weekly' | 'custom'
  since: string
  until: string
  template: string
  extraPrompt?: string
  includeMerges?: boolean
  branch?: string
}

interface ReportTemplate {
  id: string
  name: string
  description: string
  content: string
  isBuiltin: boolean
  createdAt: number
  updatedAt: number
}

// ─── 内置模板 ───────────────────────────────────────
const BUILTIN_TEMPLATES: ReportTemplate[] = [
  {
    id: 'daily-default',
    name: '日报模板',
    description: '简洁清晰的每日Git提交总结',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    content: `# 📋 Git 日报

**项目**: {{repo_name}} | **分支**: {{branch}}
**日期**: {{date_range}}

---

## 📊 概览

- 提交总数: {{commit_count}}
- 贡献者: {{contributor_count}} 人
- 文件变更: {{files_changed}} 个文件, +{{insertions}}/-{{deletions}}

## 👥 贡献者

{{contributors}}

## 📝 提交记录

{{commits}}

## 🤖 AI 总结

{{summary}}

---

> 由 Git 日报生成器自动生成 · {{generated_at}}`,
  },
  {
    id: 'weekly-default',
    name: '周报模板',
    description: '结构化的每周Git工作总结',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    content: `# 📊 Git 周报

**项目**: {{repo_name}} | **分支**: {{branch}}
**周期**: {{date_range}}

---

## 🎯 本周概览

- 提交总数: {{commit_count}}
- 活跃贡献者: {{contributor_count}} 人
- 文件变更: {{files_changed}} 个文件, +{{insertions}}/-{{deletions}}

## 👥 贡献者统计

{{contributors}}

## 📝 详细提交

{{commits}}

## 🔍 AI 深度分析

{{summary}}

## 📈 趋势与建议

{{ai_insights}}

---

> 由 Git 日报生成器自动生成 · {{generated_at}}`,
  },
  {
    id: 'github-style',
    name: 'GitHub 风格',
    description: 'GitHub Release Notes 风格排版',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    content: `# 🚀 {{repo_name}} · 更新日志

> **{{date_range}}** | 分支: \`{{branch}}\` | {{commit_count}} commits

---

## What's Changed

{{commits_github_style}}

---

## 📈 Stats

- **{{files_changed}}** files changed
- **+{{insertions}}** additions, **-{{deletions}}** deletions
- **{{contributor_count}}** contributors

## 🤖 AI Summary

{{summary}}

---

<sub>Generated by Git Report Generator · {{generated_at}}</sub>`,
  },
]

// ─── 辅助函数 ───────────────────────────────────────
function escapeShellArg(arg: string): string {
  return `'${arg.replace(/'/g, "'\\''")}'`
}

async function runGit(
  projectPath: string,
  args: string[],
  timeoutMs = 30000
): Promise<{ success: boolean; stdout: string; stderr: string }> {
  try {
    const result = await mulby.shell.runCommand({
      command: 'git',
      args: ['-C', projectPath, ...args],
      timeoutMs,
    })
    return {
      success: result.exitCode === 0,
      stdout: (result.stdout || '').trim(),
      stderr: (result.stderr || '').trim(),
    }
  } catch (e: any) {
    return { success: false, stdout: '', stderr: e?.message || String(e) }
  }
}

function getDefaultDateRange(
  reportType: 'daily' | 'weekly' | 'custom'
): { since: string; until: string } {
  const now = new Date()
  const until = now.toISOString().split('T')[0]

  let since: string
  if (reportType === 'daily') {
    const d = new Date(now)
    d.setDate(d.getDate() - 1)
    since = d.toISOString().split('T')[0]
  } else if (reportType === 'weekly') {
    const d = new Date(now)
    d.setDate(d.getDate() - 7)
    since = d.toISOString().split('T')[0]
  } else {
    const d = new Date(now)
    d.setDate(d.getDate() - 7)
    since = d.toISOString().split('T')[0]
  }

  return { since, until }
}

function formatDateForDisplay(dateStr: string): string {
  if (!dateStr) return ''
  const d = new Date(dateStr)
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

// ─── 生命周期 ───────────────────────────────────────
export function onLoad() {}
export function onUnload() {}
export function onEnable() {}
export function onDisable() {}
export async function run(_context: BackendPluginContext) {
  // 有 UI 的功能不需要在这里处理
}

// ─── RPC 方法 ───────────────────────────────────────
export const rpc = {
  /** 获取 Git 仓库基本信息 */
  async getRepoInfo(projectPath: string): Promise<RepoInfo> {
    if (!projectPath || typeof projectPath !== 'string') {
      return {
        name: '',
        path: projectPath || '',
        remoteUrl: '',
        branch: '',
        isRepo: false,
        error: '请提供有效的项目路径',
      }
    }

    const pathTrimmed = projectPath.trim()

    // 检查是否是 Git 仓库
    const checkResult = await runGit(pathTrimmed, ['rev-parse', '--is-inside-work-tree'])
    if (!checkResult.success) {
      return {
        name: pathTrimmed.split('/').pop() || pathTrimmed,
        path: pathTrimmed,
        remoteUrl: '',
        branch: '',
        isRepo: false,
        error: '该路径不是有效的 Git 仓库',
      }
    }

    // 获取仓库名
    const repoName = pathTrimmed.split('/').pop() || pathTrimmed

    // 获取远程 URL
    let remoteUrl = ''
    const remoteResult = await runGit(pathTrimmed, ['remote', 'get-url', 'origin'])
    if (remoteResult.success) {
      remoteUrl = remoteResult.stdout
    }

    // 获取当前分支
    let branch = ''
    const branchResult = await runGit(pathTrimmed, ['rev-parse', '--abbrev-ref', 'HEAD'])
    if (branchResult.success) {
      branch = branchResult.stdout
    }

    return {
      name: repoName,
      path: pathTrimmed,
      remoteUrl,
      branch,
      isRepo: true,
    }
  },

  /** 获取分支列表 */
  async getBranches(projectPath: string): Promise<{ name: string; current: boolean }[]> {
    if (!projectPath) return []

    const pathTrimmed = projectPath.trim()
    const result = await runGit(pathTrimmed, ['branch', '--format=%(refname:short)|%(HEAD)'], 10000)
    if (!result.success || !result.stdout) return []

    const branches: { name: string; current: boolean }[] = []
    for (const line of result.stdout.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed) continue
      const parts = trimmed.split('|')
      if (parts.length >= 2) {
        branches.push({
          name: parts[0],
          current: parts[1] === '*',
        })
      }
    }
    return branches
  },

  /** 获取 Git 提交日志 */
  async getGitLogs(
    projectPath: string,
    options: { since?: string; until?: string; includeMerges?: boolean; maxCommits?: number; branch?: string }
  ): Promise<GitLogResult> {
    const { since, until, includeMerges = true, maxCommits = 500, branch } = options || {}

    if (!projectPath) {
      return { commits: [], total: 0, since: since || '', until: until || '' }
    }

    const pathTrimmed = projectPath.trim()
    const args: string[] = [
      'log',
      '--format=%H|%an|%ae|%ad|%s',
      '--date=short',
      `-n`,
      String(maxCommits),
    ]

    if (since) args.push(`--since=${since}`)
    if (until) args.push(`--until=${until}`)
    if (!includeMerges) args.push('--no-merges')
    // 分支处理
    if (branch && branch !== '__current__') {
      if (branch === '__all__') {
        args.push('--all')
      } else {
        args.push(branch)
      }
    }

    const result = await runGit(pathTrimmed, args, 30000)

    const commits: CommitEntry[] = []
    if (result.success && result.stdout) {
      for (const line of result.stdout.split('\n')) {
        const parts = line.split('|')
        if (parts.length >= 5) {
          commits.push({
            hash: parts[0],
            author: parts[1],
            email: parts[2],
            date: parts[3],
            subject: parts.slice(4).join('|'),
          })
        }
      }
    }

    return {
      commits,
      total: commits.length,
      since: since || '',
      until: until || '',
    }
  },

  /** 获取贡献者统计（使用 git log 聚合，比 shortlog 更可靠） */
  async getContributors(
    projectPath: string,
    options: { since?: string; until?: string; branch?: string }
  ): Promise<ContributorStat[]> {
    const { since, until, branch } = options || {}

    if (!projectPath) return []

    const args: string[] = ['log', '--format=%an|%ae']
    if (since) args.push(`--since=${since}`)
    if (until) args.push(`--until=${until}`)
    if (branch && branch !== '__current__') {
      if (branch === '__all__') {
        args.push('--all')
      } else {
        args.push(branch)
      }
    }

    const result = await runGit(projectPath.trim(), args, 15000)

    // 聚合统计
    const map = new Map<string, ContributorStat>()
    if (result.success && result.stdout) {
      for (const line of result.stdout.split('\n')) {
        const trimmed = line.trim()
        if (!trimmed) continue
        const parts = trimmed.split('|')
        if (parts.length >= 2) {
          const name = parts[0]
          const email = parts[1]
          const key = `${name}<${email}>`
          const existing = map.get(key)
          if (existing) {
            existing.count++
          } else {
            map.set(key, { name, email, count: 1 })
          }
        }
      }
    }

    return Array.from(map.values()).sort((a, b) => b.count - a.count)
  },

  /** 获取文件变更统计（使用 git log --shortstat 聚合） */
  async getDiffStat(
    projectPath: string,
    options: { since?: string; until?: string; branch?: string }
  ): Promise<DiffStat> {
    const { since, until, branch } = options || {}

    if (!projectPath) {
      return { filesChanged: 0, insertions: 0, deletions: 0, details: '' }
    }

    const args: string[] = ['log', '--shortstat']
    if (since) args.push(`--since=${since}`)
    if (until) args.push(`--until=${until}`)
    if (branch && branch !== '__current__') {
      if (branch === '__all__') {
        args.push('--all')
      } else {
        args.push(branch)
      }
    }

    const result = await runGit(projectPath.trim(), args, 30000)
    const stdout = result.success ? result.stdout : ''

    let filesChanged = 0
    let insertions = 0
    let deletions = 0

    if (stdout) {
      // 解析多个 shortstat 行并累加
      const lines = stdout.split('\n')
      for (const line of lines) {
        const trimmed = line.trim()
        if (!trimmed) continue
        // 匹配 "3 files changed, 15 insertions(+), 5 deletions(-)"
        const match = trimmed.match(/(\d+)\s+files?\s+changed/)
        const insMatch = trimmed.match(/(\d+)\s+insertions?/)
        const delMatch = trimmed.match(/(\d+)\s+deletions?/)
        // 只累加包含统计数字的行
        if (match || insMatch || delMatch) {
          if (match) filesChanged += parseInt(match[1], 10)
          if (insMatch) insertions += parseInt(insMatch[1], 10)
          if (delMatch) deletions += parseInt(delMatch[1], 10)
        }
      }
    }

    const details = `${filesChanged} files changed, ${insertions} insertions(+), ${deletions} deletions(-)`
    return { filesChanged, insertions, deletions, details }
  },

  /** 获取当前用户 Git 配置 */
  async getGitUser(): Promise<{ name: string; email: string }> {
    try {
      const nameResult = await mulby.shell.runCommand({
        command: 'git',
        args: ['config', '--global', 'user.name'],
        timeoutMs: 5000,
      })
      const emailResult = await mulby.shell.runCommand({
        command: 'git',
        args: ['config', '--global', 'user.email'],
        timeoutMs: 5000,
      })
      return {
        name: nameResult.exitCode === 0 ? (nameResult.stdout || '').trim() : '',
        email: emailResult.exitCode === 0 ? (emailResult.stdout || '').trim() : '',
      }
    } catch {
      return { name: '', email: '' }
    }
  },

  /** 使用 AI 生成报告 */
  async generateReport(input: GenerateReportInput): Promise<{
    success: boolean
    report?: string
    error?: string
  }> {
    try {
      const {
        projectPath,
        projectPaths,
        reportType,
        since,
        until,
        template,
        extraPrompt = '',
        includeMerges = true,
        branch,
      } = input

      // 解析项目路径列表
      const allPaths: string[] = projectPaths && projectPaths.length > 0
        ? projectPaths
        : projectPath
          ? [projectPath]
          : []

      if (allPaths.length === 0) {
        return { success: false, error: '请提供至少一个项目路径' }
      }

      // 收集所有项目数据
      interface ProjectData {
        repoInfo: RepoInfo
        logResult: GitLogResult
        contributors: ContributorStat[]
        diffStat: DiffStat
      }

      const allProjects: ProjectData[] = []

      for (const p of allPaths) {
        // 获取仓库信息
        const repoInfo = await rpc.getRepoInfo(p)
        if (!repoInfo.isRepo) {
          // 跳过无效仓库，但如果只有一个项目则报错
          if (allPaths.length === 1) {
            return { success: false, error: repoInfo.error || '无效的 Git 仓库' }
          }
          continue
        }

        // 获取提交日志
        const logResult = await rpc.getGitLogs(p, {
          since,
          until,
          includeMerges,
          maxCommits: 500,
          branch,
        })

        // 获取贡献者统计
        const contributors = await rpc.getContributors(p, { since, until, branch })

        // 获取文件变更统计
        const diffStat = await rpc.getDiffStat(p, { since, until, branch })

        allProjects.push({ repoInfo, logResult, contributors, diffStat })
      }

      if (allProjects.length === 0) {
        return { success: false, error: '没有找到有效的 Git 仓库' }
      }

      // 汇总统计
      const totalCommits = allProjects.reduce((s, p) => s + p.logResult.total, 0)
      if (totalCommits === 0) {
        return {
          success: false,
          error: `在 ${formatDateForDisplay(since)} ~ ${formatDateForDisplay(until)} 期间没有找到提交记录`,
        }
      }

      // 合并贡献者（去重同名+同邮箱）
      const contributorMap = new Map<string, ContributorStat>()
      for (const p of allProjects) {
        for (const c of p.contributors) {
          const key = `${c.name}<${c.email}>`
          const existing = contributorMap.get(key)
          if (existing) {
            existing.count += c.count
          } else {
            contributorMap.set(key, { ...c })
          }
        }
      }
      const mergedContributors = Array.from(contributorMap.values()).sort(
        (a, b) => b.count - a.count
      )

      // 合并 diff 统计
      const totalFilesChanged = allProjects.reduce((s, p) => s + p.diffStat.filesChanged, 0)
      const totalInsertions = allProjects.reduce((s, p) => s + p.diffStat.insertions, 0)
      const totalDeletions = allProjects.reduce((s, p) => s + p.diffStat.deletions, 0)
      const mergedDiffStat: DiffStat = {
        filesChanged: totalFilesChanged,
        insertions: totalInsertions,
        deletions: totalDeletions,
        details: `${totalFilesChanged} files changed, ${totalInsertions} insertions(+), ${totalDeletions} deletions(-)`,
      }

      // 构建项目信息文本
      const repoNameText =
        allPaths.length === 1
          ? allProjects[0].repoInfo.name
          : allProjects.map((p) => p.repoInfo.name).join(', ')
      const branchText = branch && branch !== '__current__'
        ? (branch === '__all__' ? '所有分支' : branch)
        : allPaths.length === 1
          ? allProjects[0].repoInfo.branch
          : '多项目'
      const repoListText = allProjects
        .map((p) => `- **${p.repoInfo.name}** (${p.repoInfo.branch}): ${p.logResult.total} commits`)
        .join('\n')

      // 构建提交列表文本（合并所有项目）
      const commitsText = allProjects
        .flatMap((p) =>
          p.logResult.commits.map(
            (c) =>
              `[${p.repoInfo.name}] \`${c.hash.slice(0, 7)}\` **${c.author}** - ${c.subject} (${c.date})`
          )
        )
        .sort((a, b) => {
          // 按日期排序（提取日期部分比较）
          const da = a.match(/\((\d{4}-\d{2}-\d{2})\)$/)?.[1] || ''
          const db = b.match(/\((\d{4}-\d{2}-\d{2})\)$/)?.[1] || ''
          return db.localeCompare(da) // 降序
        })
        .map((c, i) => `${i + 1}. ${c}`)
        .join('\n')

      const commitsGitHubStyle = allProjects
        .flatMap((p) =>
          p.logResult.commits.map(
            (c) => `* [${p.repoInfo.name}] ${c.subject} (@${c.author} in \`${c.hash.slice(0, 7)}\`)`
          )
        )
        .join('\n')

      const contributorsText = mergedContributors
        .map((c, i) => `${i + 1}. **${c.name}** - ${c.count} commits`)
        .join('\n')

      // 日期范围显示
      const dateRange =
        reportType === 'daily'
          ? formatDateForDisplay(since)
          : `${formatDateForDisplay(since)} ~ ${formatDateForDisplay(until)}`

      // 构建 AI 提示词
      const reportTypeLabel =
        reportType === 'daily' ? '日报' : reportType === 'weekly' ? '周报' : 'Git 报告'

      const multiProjectHint =
        allPaths.length > 1
          ? `\n注意：本次分析包含 ${allPaths.length} 个项目，请在报告中按项目分别总结。`
          : ''

      const systemPrompt = `你是一位资深的软件开发团队技术负责人，擅长根据 Git 提交记录撰写清晰、专业的${reportTypeLabel}。

要求：
1. 用中文撰写报告
2. 按照提交内容归类总结（如：新功能、Bug修复、重构、文档、性能优化等）
3. 指出重要的、影响大的变更
4. 语言简洁专业，适合团队内部沟通
5. 使用 Markdown 格式输出
6. 不要忽略任何提交，尽量覆盖所有变更${multiProjectHint}
${extraPrompt ? `\n额外要求：${extraPrompt}` : ''}`

      const userPrompt = `请根据以下 Git 提交记录，生成一份${reportTypeLabel}。

**项目**: ${repoNameText}
**分支**: ${branchText}
**时间范围**: ${dateRange}
**分析项目数**: ${allPaths.length}

${allPaths.length > 1 ? `**项目列表**:\n${repoListText}\n` : ''}

**提交统计**:
- 总提交数: ${totalCommits}
- 贡献者: ${mergedContributors.length} 人
- 文件变更: ${mergedDiffStat.filesChanged} 个文件, +${mergedDiffStat.insertions}/-${mergedDiffStat.deletions}

**贡献者详情**:
${contributorsText}

**提交记录**:
${commitsText}

请生成一份结构清晰、有分类总结的${reportTypeLabel}。直接输出 Markdown 格式的最终报告（不需要输出分析过程）。`

      // 调用 AI
      const aiResponse = await mulby.ai.call({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
      })

      const aiSummary = (aiResponse.content as string) || ''

      // 填充模板
      const now = new Date().toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })
      let finalReport = template
        .replace(/\{\{repo_name\}\}/g, repoNameText)
        .replace(/\{\{branch\}\}/g, branchText)
        .replace(/\{\{remote_url\}\}/g, allProjects[0]?.repoInfo.remoteUrl || '无')
        .replace(/\{\{date_range\}\}/g, dateRange)
        .replace(/\{\{commit_count\}\}/g, String(totalCommits))
        .replace(/\{\{contributor_count\}\}/g, String(mergedContributors.length))
        .replace(/\{\{files_changed\}\}/g, String(mergedDiffStat.filesChanged))
        .replace(/\{\{insertions\}\}/g, String(mergedDiffStat.insertions))
        .replace(/\{\{deletions\}\}/g, String(mergedDiffStat.deletions))
        .replace(/\{\{contributors\}\}/g, contributorsText || '无')
        .replace(/\{\{commits_github_style\}\}/g, commitsGitHubStyle || '无')
        .replace(/\{\{commits\}\}/g, commitsText || '无')
        .replace(/\{\{summary\}\}/g, aiSummary || '（AI 总结生成中...）')
        .replace(/\{\{ai_insights\}\}/g, '')
        .replace(/\{\{generated_at\}\}/g, now)
        .replace(/\{\{diff_details\}\}/g, mergedDiffStat.details)
        .replace(/\{\{repo_list\}\}/g, repoListText)

      return { success: true, report: finalReport }
    } catch (e: any) {
      return {
        success: false,
        error: e?.message || '生成报告时发生未知错误',
      }
    }
  },

  /** 列出所有模板（内置 + 自定义） */
  async listTemplates(): Promise<ReportTemplate[]> {
    try {
      const customStr = await mulby.storage.get('custom_templates', 'git-report-generator')
      const custom: ReportTemplate[] = customStr ? JSON.parse(customStr as string) : []
      return [...BUILTIN_TEMPLATES, ...custom]
    } catch {
      return [...BUILTIN_TEMPLATES]
    }
  },

  /** 获取单个模板 */
  async getTemplate(templateId: string): Promise<ReportTemplate | null> {
    const all = await rpc.listTemplates()
    return all.find((t) => t.id === templateId) || null
  },

  /** 保存自定义模板 */
  async saveTemplate(template: {
    id?: string
    name: string
    description: string
    content: string
  }): Promise<{ success: boolean; template?: ReportTemplate; error?: string }> {
    try {
      if (!template.name || !template.content) {
        return { success: false, error: '模板名称和内容不能为空' }
      }

      const customStr = await mulby.storage.get('custom_templates', 'git-report-generator')
      const custom: ReportTemplate[] = customStr ? JSON.parse(customStr as string) : []

      const now = Date.now()
      const id = template.id || `custom-${now}`

      const newTemplate: ReportTemplate = {
        id,
        name: template.name,
        description: template.description,
        content: template.content,
        isBuiltin: false,
        createdAt: now,
        updatedAt: now,
      }

      const existingIdx = custom.findIndex((t) => t.id === id)
      if (existingIdx >= 0) {
        newTemplate.createdAt = custom[existingIdx].createdAt
        custom[existingIdx] = newTemplate
      } else {
        custom.push(newTemplate)
      }

      await mulby.storage.set('custom_templates', JSON.stringify(custom), 'git-report-generator')
      return { success: true, template: newTemplate }
    } catch (e: any) {
      return { success: false, error: e?.message || '保存模板失败' }
    }
  },

  /** 删除自定义模板 */
  async deleteTemplate(
    templateId: string
  ): Promise<{ success: boolean; error?: string }> {
    try {
      const customStr = await mulby.storage.get('custom_templates', 'git-report-generator')
      const custom: ReportTemplate[] = customStr ? JSON.parse(customStr as string) : []

      const idx = custom.findIndex((t) => t.id === templateId)
      if (idx < 0) {
        return { success: false, error: '模板不存在' }
      }

      custom.splice(idx, 1)
      await mulby.storage.set('custom_templates', JSON.stringify(custom), 'git-report-generator')
      return { success: true }
    } catch (e: any) {
      return { success: false, error: e?.message || '删除模板失败' }
    }
  },

  /** 重置所有自定义模板 */
  async resetTemplates(): Promise<{ success: boolean }> {
    try {
      await mulby.storage.remove('custom_templates', 'git-report-generator')
      return { success: true }
    } catch {
      return { success: false }
    }
  },
}

const plugin = { onLoad, onUnload, onEnable, onDisable, run, rpc }
export default plugin
