import './search.test'
import './image.test'
import './ai.test'
import './bubble.test'
import './markdown.test'
import './imageGen.test'
import './imageHistory.test'
import './contextMenu.test'
import './filePath.test'
import './fileTree.test'
import './recentFiles.test'
import './tabs.test'
import './session.test'
import './diff.test'
import '../editor/livePreviewModel.test'
import '../editor/listFold.test'
import '../editor/tableModel.test'
import './export/enhance.test'

console.log('markdown-editor unit tests passed')
