// 构建期脚本：从 lucide-static 抽取精选图标，生成自包含的 src/shared/icons.ts。
// 运行时不依赖 lucide-static（仅 devDependency）。
// 用法：node scripts/gen-icons.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const iconsDir = resolve(root, 'node_modules/lucide-static/icons')

// 精选图标：name(lucide 文件名) + 中文标签。按用途分组排列。
const CURATED = [
  // 搜索 / 网页
  ['search', '搜索'], ['globe', '网页'], ['compass', '导航'], ['languages', '翻译'],
  ['book-open', '文档'], ['graduation-cap', '学习'], ['newspaper', '资讯'], ['map', '地图'],
  // 开发
  ['code', '代码'], ['code-xml', '标记'], ['terminal', '终端'], ['git-branch', 'Git'],
  ['database', '数据库'], ['bug', '调试'], ['braces', 'JSON'], ['cpu', '系统'],
  ['server', '服务器'], ['container', '容器'],
  // 文件 / 存储
  ['folder', '文件夹'], ['folder-open', '打开目录'], ['file', '文件'], ['file-text', '文档文件'],
  ['hard-drive', '磁盘'], ['cloud', '云'], ['download', '下载'], ['archive', '归档'],
  // 通讯
  ['mail', '邮件'], ['message-circle', '消息'], ['send', '发送'], ['phone', '电话'], ['rss', '订阅'],
  // 媒体
  ['music', '音乐'], ['video', '视频'], ['film', '影视'], ['image', '图片'], ['play', '播放'],
  ['headphones', '音频'], ['camera', '相机'], ['tv', '电视'],
  // 效率 / 通用
  ['calendar', '日历'], ['clock', '时间'], ['list-todo', '待办'], ['bookmark', '书签'],
  ['star', '收藏'], ['heart', '喜欢'], ['pin', '钉住'], ['flag', '标记'],
  ['settings', '设置'], ['wrench', '工具'], ['zap', '快捷'], ['rocket', '启动'],
  ['layers', '工作区'], ['link', '链接'], ['external-link', '外链'], ['shopping-cart', '购物'],
  ['briefcase', '工作'], ['building', '公司'], ['home', '主页'], ['user', '用户'],
  ['lock', '锁'], ['key', '密钥'], ['shield', '安全'], ['palette', '设计'],
  ['monitor', '显示器'], ['smartphone', '手机'], ['wifi', '网络'], ['package', '包'],
  ['gift', '礼物'], ['coffee', '休息'], ['gamepad-2', '游戏'], ['bot', '机器人'],
  ['sparkles', '亮点'], ['command', '命令'], ['layout-grid', '面板'], ['box', '盒子']
]

function extractBody(svg) {
  // 去掉 license 注释，提取 <svg ...> 与 </svg> 之间的子节点，并压缩空白
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)
  if (!m) return null
  return m[1].replace(/\s*\n\s*/g, '').replace(/>\s+</g, '><').trim()
}

const out = []
const missing = []
for (const [name, label] of CURATED) {
  const file = resolve(iconsDir, `${name}.svg`)
  if (!existsSync(file)) {
    missing.push(name)
    continue
  }
  const body = extractBody(readFileSync(file, 'utf8'))
  if (!body) {
    missing.push(name)
    continue
  }
  out.push({ name, label, body })
}

const header = `// AUTO-GENERATED by scripts/gen-icons.mjs — DO NOT EDIT.
// 图标源：lucide-static (ISC License)。运行时不依赖 lucide-static。
export interface IconDef {
  name: string
  label: string
  body: string
}

export const ICONS: IconDef[] = ${JSON.stringify(out, null, 2)}

export const ICON_MAP: Record<string, string> = Object.fromEntries(
  ICONS.map((i) => [i.name, i.body])
)

export function hasIcon(name?: string): boolean {
  return !!name && Object.prototype.hasOwnProperty.call(ICON_MAP, name)
}
`

const target = resolve(root, 'src/shared/icons.ts')
writeFileSync(target, header, 'utf8')
console.log(`生成 ${out.length} 个图标 -> ${target}`)
if (missing.length) console.warn(`跳过(不存在): ${missing.join(', ')}`)
